//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeapadToolkit.WinUI3.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdeapadToolkit.WinUI3.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app is already running.
        /// </summary>
        public static string ALREADY_RUNNING {
            get {
                return ResourceManager.GetString("ALREADY_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on USB.
        /// </summary>
        public static string ALWAYS_ON_USB {
            get {
                return ResourceManager.GetString("ALWAYS_ON_USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on USB on battery.
        /// </summary>
        public static string ALWAYS_ON_USB_BATTERY {
            get {
                return ResourceManager.GetString("ALWAYS_ON_USB_BATTERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Charging Mode.
        /// </summary>
        public static string BATTERY_CHARGING_MODE {
            get {
                return ResourceManager.GetString("BATTERY_CHARGING_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Saving.
        /// </summary>
        public static string BATTERY_SAVING {
            get {
                return ResourceManager.GetString("BATTERY_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conservation.
        /// </summary>
        public static string CONSERVATION {
            get {
                return ResourceManager.GetString("CONSERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerBattery.dll has to be present in the same folder as IdeapadToolkit.exe.
        /// </summary>
        public static string DLL_MISSING_ERROR {
            get {
                return ResourceManager.GetString("DLL_MISSING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Performance.
        /// </summary>
        public static string EXTREME_PERFORMANCE {
            get {
                return ResourceManager.GetString("EXTREME_PERFORMANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip to Boot.
        /// </summary>
        public static string FLIP_TO_BOOT {
            get {
                return ResourceManager.GetString("FLIP_TO_BOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Cooling.
        /// </summary>
        public static string INTELLIGENT_COOLING {
            get {
                return ResourceManager.GetString("INTELLIGENT_COOLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep running in the background.
        /// </summary>
        public static string KEEP_IN_TRAY {
            get {
                return ResourceManager.GetString("KEEP_IN_TRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NORMAL {
            get {
                return ResourceManager.GetString("NORMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OTHER {
            get {
                return ResourceManager.GetString("OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Profile.
        /// </summary>
        public static string POWER_PROFILE {
            get {
                return ResourceManager.GetString("POWER_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid.
        /// </summary>
        public static string RAPID {
            get {
                return ResourceManager.GetString("RAPID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run On Startup.
        /// </summary>
        public static string RUN_ON_STARTUP {
            get {
                return ResourceManager.GetString("RUN_ON_STARTUP", resourceCulture);
            }
        }
    }
}
